testing workflow

diff --git a/.github/workflows/terraform-fmt.yml b/.github/workflows/terraform-fmt.yml
--- a/.github/workflows/terraform-fmt.yml
+++ b/.github/workflows/terraform-fmt.yml
@@ -30,13 +30,18 @@ jobs:
       # Run Terraform FMT and check if files are formatted correctly
       - name: Check Terraform Formatting
         id: terraform_fmt
-        run: terraform fmt -check -recursive || (terraform fmt -recursive && echo "The following files are not formatted:" && terraform fmt -diff -recursive && exit 1)
+        run: terraform fmt -check -recursive
+        continue-on-error: true
 
       # Output which files are not formatted correctly
       - name: Show Unformatted Files
-        if: failure()  # Only run if the previous step fails
-        run: terraform fmt -diff -recursive
+        if: failure()
+        run: terraform fmt -recursive -diff
 
+      # Fail the workflow if there are unformatted files
+      - name: Fail if not formatted
+        if: failure()
+        run: exit 1
 
 
         # How it works:
